document.write("<!DOCTYPE html>");
document.write("<html>");
document.write("<head>");
document.write("	<title><\/title>");
document.write("");
document.write("<\/head>");
document.write("<body>");
document.write("<section style=\"padding: 0 20px 30px 20px;\" class=\"meds\">");
document.write("        <!--<div align=\"center\">");
document.write("            <div class=\"row\">");
document.write("                <div class=\"col-lg-12\">");
document.write("                    <img src=\"images\/hero-2.jpg\" class=\"img-responsive\" style=\"border-radius: 40px; width: 100%;\">");
document.write("                <\/div>");
document.write("            <\/div>-->");
document.write("            <picture>");
document.write("   <source media=\"(min-width: 650px)\" srcset=\"images\/18.png\">");
document.write("   <source media=\"(min-width: 1px)\" srcset=\"images\/19.png\">");
document.write("   <img src=\"images\/18.png\" alt=\"error\"  style=\"width: 100%;\">");
document.write("<\/picture>");
document.write("");
document.write("    <\/section>");
document.write("<\/body>");
document.write("<\/html>");
