document.write("<!DOCTYPE html>");
document.write("<html>");
document.write("<head>");
document.write("	<title><\/title>");
document.write("	   <!-- Css Styles -->");
document.write("    <link rel=\"stylesheet\" href=\"css\/bootstrap.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/font-awesome.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/elegant-icons.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/magnific-popup.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/nice-select.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/owl.carousel.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/slicknav.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/style.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/mine.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/OwlCarousel2\/2.3.4\/assets\/owl.carousel.min.css\">");
document.write("<link rel=\"stylesheet\" href=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/OwlCarousel2\/2.3.4\/assets\/owl.theme.default.min.css\">");
document.write("<link rel=\"preconnect\" href=\"https:\/\/fonts.gstatic.com\">");
document.write("<link href=\"https:\/\/fonts.googleapis.com\/css2?family=Lato&family=Montserrat&family=Oswald&family=Raleway&family=Roboto&display=swap\" rel=\"stylesheet\">");
document.write("");
document.write("<\/head>");
document.write("<body>");
document.write("    <section class=\"remarkable\">");
document.write("      <div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-ride=\"carousel\" data-interval=\"2000\">");
document.write("  <ol class=\"carousel-indicators\">");
document.write("    <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\" class=\"active\"><\/li>");
document.write("    <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"><\/li>");
document.write("    <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"><\/li>");
document.write("    <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"3\"><\/li>");
document.write("");
document.write("  <\/ol>");
document.write("  <div class=\"carousel-inner\">");
document.write("     <div class=\"carousel-item active\">");
document.write("      <picture class=\"d-block w-100\">");
document.write("   <source media=\"(max-width: 650px)\" srcset=\"images\/27.png\">");
// document.write("   <source media=\"(min-width: 1px)\" srcset=\"images\/27.png\">");
document.write("   <img src=\"images\/26.png\" alt=\"error\"  style=\"width: 100%;\">");
document.write("<\/picture>");
document.write("    <\/div>");
document.write("     <div class=\"carousel-item\">");
document.write("      <picture class=\"d-block w-100\">");
document.write("   <source media=\"(max-width: 650px)\" srcset=\"images\/25.png\">");
// document.write("   <source media=\"(min-width: 1px)\" srcset=\"images\/25.png\">");
document.write("   <img src=\"images\/24.png\" alt=\"error\"  style=\"width: 100%;\">");
document.write("<\/picture>");
document.write("    <\/div>");
document.write("    <div class=\"carousel-item\">");
document.write("        <picture class=\"d-block w-100\">");
document.write("   <source media=\"(max-width: 650px)\" srcset=\"images\/21.png\">");
// document.write("   <source media=\"(min-width: 1px)\" srcset=\"images\/21.png\">");
document.write("   <img src=\"images\/20.png\" alt=\"error\"  style=\"width: 100%;\">");
document.write("<\/picture>");
document.write("    <\/div>");
document.write("    <div class=\"carousel-item\">");
document.write("      <picture class=\"d-block w-100\">");
document.write("   <source media=\"(max-width: 650px)\" srcset=\"images\/8.jpg\">");
// document.write("   <source media=\"(min-width: 1px)\" srcset=\"images\/8.jpg\">");
document.write("   <img src=\"images\/7.jpg\" alt=\"error\"  style=\"width: 100%;\">");
document.write("<\/picture>");
document.write("    <\/div>");
document.write("    <div class=\"carousel-item\">");
document.write("      <picture class=\"d-block w-100\">");
document.write("   <source media=\"(max-width: 650px)\" srcset=\"images\/23.png\">");
// document.write("   <source media=\"(min-width: 1px)\" srcset=\"images\/23.png\">");
document.write("   <img src=\"images\/22.png\" alt=\"error\"  style=\"width: 100%;\">");
document.write("<\/picture>");
document.write("    <\/div>");
document.write("   ");
document.write("  <\/div>");
document.write("  <a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"prev\">");
document.write("    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"><\/span>");
document.write("    <span class=\"sr-only\">Previous<\/span>");
document.write("  <\/a>");
document.write("  <a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"next\">");
document.write("    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"><\/span>");
document.write("    <span class=\"sr-only\">Next<\/span>");
document.write("  <\/a>");
document.write("<\/div>");
document.write("<\/section>");
document.write("<\/body>");
document.write("");
document.write("    <script src=\"js\/jquery-3.3.1.min.js\"><\/script>");
document.write("    <script src=\"js\/bootstrap.min.js\"><\/script>");
document.write("    <script src=\"js\/jquery.nice-select.min.js\"><\/script>");
// document.write("    <script src=\"js\/jquery.nicescroll.min.js\"><\/script>");
document.write("    <script src=\"js\/jquery.magnific-popup.min.js\"><\/script>");
document.write("    <script src=\"js\/jquery.countdown.min.js\"><\/script>");
document.write("    <script src=\"js\/jquery.slicknav.js\"><\/script>");
// document.write("    <script src=\"js\/mixitup.min.js\"><\/script>");
// document.write("    <script src=\"js\/owl.carousel.min.js\"><\/script>");
document.write("    <script src=\"js\/main.js\"><\/script>");
document.write("    <script src=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/jquery\/3.3.1\/jquery.min.js\"><\/script>");
document.write("<script src=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/OwlCarousel2\/2.3.4\/owl.carousel.min.js\"><\/script>");
document.write("<\/html>");
