document.write("<!DOCTYPE html>");
document.write("<html lang=\"zxx\">");
document.write("");
document.write("<head>");
document.write("    <meta charset=\"UTF-8\">");
document.write("    <meta name=\"description\" content=\"Male_Fashion Template\">");
document.write("    <meta name=\"keywords\" content=\"Male_Fashion, unica, creative, html\">");
document.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.\">");
document.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">");
document.write("    <title>Novatio Официальный Сайт<\/title>");
document.write("    <link rel=\"shortcut icon\" href=\"images\/logog\/favicon2.png\" type=\"image\/png\">");
document.write("");
document.write("    <!-- Google Font -->");
document.write("    <link href=\"https:\/\/fonts.googleapis.com\/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap\"");
document.write("    rel=\"stylesheet\">");
document.write("     <link href=\"https:\/\/fonts.googleapis.com\/css?family=Montserrat\"");
document.write("    rel=\"stylesheet\">");
document.write("");
document.write("    <!-- Css Styles -->");
document.write("    <link rel=\"stylesheet\" href=\"css\/bootstrap.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/font-awesome.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/elegant-icons.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/magnific-popup.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/nice-select.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/owl.carousel.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/slicknav.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/style.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/mine.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/OwlCarousel2\/2.3.4\/assets\/owl.carousel.min.css\">");
document.write("<link rel=\"stylesheet\" href=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/OwlCarousel2\/2.3.4\/assets\/owl.theme.default.min.css\">");
document.write("<link rel=\"preconnect\" href=\"https:\/\/fonts.gstatic.com\">");
document.write("<link href=\"https:\/\/fonts.googleapis.com\/css2?family=Lato&family=Montserrat&family=Oswald&family=Raleway&family=Roboto&display=swap\" rel=\"stylesheet\">");
document.write("");
document.write("<\/head>");
document.write("");
document.write("<body>");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("");
document.write("<section>");
document.write("    <div class=\"container\">");
document.write("        <div class=\"row\">");
document.write("                <div class=\"col-lg-12\">");
document.write("                    <div class=\"section-title\">");
document.write("                        <span>novatio - tabiiy zo'r<\/span>");
document.write("                        <h2 class=\"fuku\">Ценности Novatio<\/h2>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("        <div class=\"row\">");
document.write("            <div class=\"col-lg-6\">");
document.write("                 <picture>");
document.write("   <source media=\"(min-width: 650px)\" srcset=\"images\/v_1.webp\">");
document.write("   <img src=\"images\/v_1.png\" alt=\"error\"  style=\"width: 100%;\">");
document.write("<\/picture>");
document.write("            <\/div>");
document.write("            <div class=\"col-lg-6\">");
document.write("                <picture>");
document.write("   <source media=\"(min-width: 650px)\" srcset=\"images\/v_2.webp\">");
document.write("   <img src=\"images\/v_2.png\" alt=\"error\"  style=\"width: 100%;\">");
document.write("<\/picture>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("        <div class=\"row\">");
document.write("            <div class=\"col-lg-6\">");
document.write("                 <picture>");
document.write("   <source media=\"(min-width: 650px)\" srcset=\"images\/v_3.webp\">");
document.write("   <img src=\"images\/v_3.png\" alt=\"error\"  style=\"width: 100%;\">");
document.write("<\/picture>");
document.write("            <\/div>");
document.write("            <div class=\"col-lg-6\">");
document.write("                <picture>");
document.write("   <source media=\"(min-width: 650px)\" srcset=\"images\/v_4.webp\">");
document.write("   <img src=\"images\/v_4.png\" alt=\"error\"  style=\"width: 100%;\">");
document.write("<\/picture>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("        <div class=\"row\">");
document.write("            <div class=\"col-lg-6\">");
document.write("                 <picture>");
document.write("   <source media=\"(min-width: 650px)\" srcset=\"images\/v_5.webp\">");
document.write("   <img src=\"images\/v_5.png\" alt=\"error\"  style=\"width: 100%;\">");
document.write("<\/picture>");
document.write("            <\/div>");
document.write("            <div class=\"col-lg-6\">");
document.write("                <picture>");
document.write("   <source media=\"(min-width: 650px)\" srcset=\"images\/v_6.webp\">");
document.write("   <img src=\"images\/v_6.png\" alt=\"error\"  style=\"width: 100%;\">");
document.write("<\/picture>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("        <div class=\"row\">");
document.write("            <div class=\"col-lg-6\">");
document.write("                 <picture>");
document.write("   <source media=\"(min-width: 650px)\" srcset=\"images\/v_7.webp\">");
document.write("   <img src=\"images\/v_7.png\" alt=\"error\"  style=\"width: 100%;\">");
document.write("<\/picture>");
document.write("            <\/div>");
document.write("            <div class=\"col-lg-6\">");
document.write("                <picture>");
document.write("   <source media=\"(min-width: 650px)\" srcset=\"images\/v_8.webp\">");
document.write("   <img src=\"images\/v_8.png\" alt=\"error\"  style=\"width: 100%;\">");
document.write("<\/picture>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("    <\/div>");
document.write("<\/section>");
document.write("");
document.write("   ");
document.write("");
document.write("");
document.write("");
document.write("    <!-- Search Begin -->");
document.write("    <div class=\"search-model\">");
document.write("        <div class=\"h-100 d-flex align-items-center justify-content-center\">");
document.write("            <div class=\"search-close-switch\">+<\/div>");
document.write("            <form class=\"search-model-form\">");
document.write("                <input type=\"text\" id=\"search-input\" placeholder=\"Search here.....\">");
document.write("            <\/form>");
document.write("        <\/div>");
document.write("    <\/div>");
document.write("    <!-- Search End -->");
document.write("");
document.write("    <!-- Js Plugins -->");
document.write("    <script src=\"js\/jquery-3.3.1.min.js\"><\/script>");
document.write("    <script src=\"js\/bootstrap.min.js\"><\/script>");
document.write("    <script src=\"js\/jquery.nice-select.min.js\"><\/script>");
document.write("    <script src=\"js\/jquery.nicescroll.min.js\"><\/script>");
document.write("    <script src=\"js\/jquery.magnific-popup.min.js\"><\/script>");
document.write("    <script src=\"js\/jquery.countdown.min.js\"><\/script>");
document.write("    <script src=\"js\/jquery.slicknav.js\"><\/script>");
document.write("    <script src=\"js\/mixitup.min.js\"><\/script>");
document.write("    <script src=\"js\/owl.carousel.min.js\"><\/script>");
document.write("    <script src=\"js\/main.js\"><\/script>");
document.write("    <script src=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/jquery\/3.3.1\/jquery.min.js\"><\/script>");
document.write("<script src=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/OwlCarousel2\/2.3.4\/owl.carousel.min.js\"><\/script>");
document.write("<\/body>");
document.write("");
document.write("<\/html>");
