document.write("<!DOCTYPE html>");
document.write("<html>");
document.write("<head>");
document.write("    <title>HEADER<\/title>");
document.write("      <!-- Google Font -->");
document.write("    <link href=\"https:\/\/fonts.googleapis.com\/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap\"");
document.write("    rel=\"stylesheet\">");
document.write("     <link href=\"https:\/\/fonts.googleapis.com\/css?family=Montserrat\"");
document.write("    rel=\"stylesheet\">");
document.write("");
document.write("    <!-- Css Styles -->");
document.write("    <link rel=\"stylesheet\" href=\"css\/bootstrap.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/font-awesome.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/elegant-icons.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/magnific-popup.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/nice-select.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/owl.carousel.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/slicknav.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/style.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/mine.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/OwlCarousel2\/2.3.4\/assets\/owl.carousel.min.css\">");
document.write("<link rel=\"stylesheet\" href=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/OwlCarousel2\/2.3.4\/assets\/owl.theme.default.min.css\">");
document.write("<link rel=\"preconnect\" href=\"https:\/\/fonts.gstatic.com\">");
document.write("<link href=\"https:\/\/fonts.googleapis.com\/css2?family=Lato&family=Montserrat&family=Oswald&family=Raleway&family=Roboto&display=swap\" rel=\"stylesheet\">");
document.write("");
document.write("<\/head>");
document.write("<body>");
document.write("     <!-- Footer Section Begin -->");
document.write("   <footer id=\"contacts\" class=\"footer\" style=\"background: url(images\/footer.webp); background-size: cover; background-position: center; background-repeat: no-repeat; \">");
document.write("        <div class=\"container \">");
document.write("            <div class=\"row white_gray\">");
document.write("                <div class=\"col-lg-4 col-md-12 col-sm-12\">");
document.write("                    <div class=\"footer__about\">");
document.write("                        <div class=\"footer__logo\" align=\"center\">");
document.write("                            <a href=\"index.html\"><img src=\"images\/logog\/logo_black.png\" class=\"logo_h\"><\/a>");
document.write("                        <\/div>");
document.write("                        <p style=\"color: #565656; margin-left: 5%; margin-right: 5%\"align=\"center\">Помогаем приобрести Внутренний Баланс Тела и Души.<\/p>");
document.write("");
// document.write("                        <a href=\"#\"><img src=\"img\/payment.png\" alt=\"\"><\/a>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <div class=\"col-lg-2 col-md-6 col-sm-12\">");
document.write("                    <div class=\"footer__widget al_c\">");
document.write("                        <h6>Компания<\/h6>");
document.write("                        <ul>");
document.write("                            <li><a href=\"index.html#mission\">Миссия<\/a><\/li>");
document.write("                            <li><a href=\"index.htmlshop.html\">Продукция<\/a><\/li>");
document.write("                            <li><a href=\"index.html#values\">Ценности<\/a><\/li>");
document.write("                            <li><a href=\"index.html#blog\">Блог<\/a><\/li>");
document.write("");
document.write("                        <\/ul>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                 <div class=\"col-lg-2 col-md-6 col-sm-6\">");
document.write("                    <div class=\"footer__widget al_c\" >");
document.write("                        <h6>Мы рядом<\/h6>");
document.write("                         <ul>");
document.write("                            <li><a href=\"https:\/\/www.facebook.com\/soglomhayotnovatio\/\">Facebook<\/a><\/li>");
document.write("                            <li><a href=\"https:\/\/www.instagram.com\/soglomhayot_novatio\/\">Instagram<\/a><\/li>");
document.write("                            <li><a href=\"https:\/\/www.youtube.com\/channel\/UCdZLVSVKBqlz3W0FlybV-Kw\/featured\">YouTube<\/a><\/li>");
document.write("                            <li><a href=\"https:\/\/t.me\/soglomhayotnovatio\">Telegram<\/a><\/li>");
document.write("");
document.write("                        <\/ul>");
document.write("                    <\/div>");
document.write("                     ");
document.write("                <\/div>");
document.write("                <div class=\"col-lg-2 col-md-6 col-sm-6\">");
document.write("                    <div class=\"footer__widget al_c\">");
document.write("                        <h6>Карьера<\/h6>                        ");
document.write("                        <ul>");
document.write("                            <li><a href=\"rabota.new\/index.html\">Работа в NOVATIO<\/a><\/li>");
document.write("                            <li><a href=\"rabota.new\/index.html\">Академия NOVATIO<\/a><\/li>");
document.write("");
document.write("                        <\/ul>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                  <div class=\"col-lg-2 col-md-6 col-sm-6\">");
document.write("                    <div class=\"footer__widget al_c\">");
document.write("                        <h6>Контакты<\/h6>                        ");
document.write("                        <ul>");
document.write("                            <li><a>+998(71) 200-11-66<\/a><\/li>");
document.write("                            <li><a>+998(93) 389-35-00<\/a><\/li>");
document.write("                        <\/ul>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("               ");
document.write("            <\/div>");
document.write("            <div class=\"row\" style=\"\">");
document.write("                <div class=\"col-lg-6 l-al\">");
document.write("                     <div class=\"hero__social\">");
document.write("                                    <a href=\"https:\/\/www.facebook.com\/soglomhayotnovatio\/\"><i class=\"fa fa-facebook\" ><\/i><\/a>");
document.write("                                    <a href=\"https:\/\/t.me\/soglomhayotnovatio\"><i class=\"fa fa-telegram\" ><\/i><\/a>");
document.write("                                     <a href=\"https:\/\/www.instagram.com\/soglomhayot_novatio\/\"><i class=\"fa fa-instagram\" ><\/i><\/a>");
document.write("                                    <a href=\"https:\/\/www.youtube.com\/channel\/UCdZLVSVKBqlz3W0FlybV-Kw\/featured\"><i class=\"fa fa-youtube\" ><\/i><\/a>");
document.write("                                <\/div>");
document.write("                    ");
document.write("                <\/div>");
document.write("                <div class=\"col-lg-6 l-ri\">");
document.write("                      <div class=\"footer__copyright__text\">");
document.write("                        <a href=\"index.html\"><img src=\"images\/ru.png\" width=\"10%\"><\/a>");
document.write("                            <a href=\"index_en.html\"><img src=\"images\/eng.png\" width=\"10%\"><\/a>");
document.write("                        <p style=\"color: white;\">© Novatio tabiiy zo'r, 2020 All rights reserved. made by <strong>YK<\/strong>");
document.write("                        <\/p>");
document.write("                    <\/div> ");
document.write("                <\/div>");
document.write("                ");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("    <\/footer>");
document.write("    <!-- Footer Section End -->");
document.write("<\/body>");
document.write("<\/html>");
