document.write("<!DOCTYPE html>");
document.write("<html>");
document.write("<head>");
document.write("    <title>HEADER<\/title>");
document.write("      <!-- Google Font -->");
document.write("    <link href=\"https:\/\/fonts.googleapis.com\/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap\"");
document.write("    rel=\"stylesheet\">");
document.write("     <link href=\"https:\/\/fonts.googleapis.com\/css?family=Montserrat\"");
document.write("    rel=\"stylesheet\">");
document.write("");
document.write("    <!-- Css Styles -->");
document.write("    <link rel=\"stylesheet\" href=\"css\/bootstrap.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/font-awesome.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/elegant-icons.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/magnific-popup.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/nice-select.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/owl.carousel.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/slicknav.min.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/style.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/mine.css\" type=\"text\/css\">");
document.write("    <link rel=\"stylesheet\" href=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/OwlCarousel2\/2.3.4\/assets\/owl.carousel.min.css\">");
document.write("<link rel=\"stylesheet\" href=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/OwlCarousel2\/2.3.4\/assets\/owl.theme.default.min.css\">");
document.write("<link rel=\"preconnect\" href=\"https:\/\/fonts.gstatic.com\">");
document.write("<link href=\"https:\/\/fonts.googleapis.com\/css2?family=Lato&family=Montserrat&family=Oswald&family=Raleway&family=Roboto&display=swap\" rel=\"stylesheet\">");
document.write("");
document.write("<\/head>");
document.write("<body>");
document.write("      <!-- Offcanvas Menu Begin -->");
document.write("    <div class=\"offcanvas-menu-overlay\"><\/div>");
document.write("    <div class=\"offcanvas-menu-wrapper\">");
document.write("        <div class=\"offcanvas__option\">");
document.write("            <div class=\"offcanvas__links\">");
document.write("                <a href=\".\/index.html\"><img src=\"images\/logog\/logo_classic.png\" alt=\"\"><\/a>");
document.write("                 <div class=\"\"><a href=\"rabota.new\/index.html\"><img src=\"images\/14(d).png\" style=\"width: 80%; margin-top: 20px\"><\/a><\/div>");
document.write("            <\/div>");
document.write("           ");
document.write("        <\/div>");
document.write("       ");
document.write("<nav class=\"mobile-menu\">");
document.write("                        <ul class=\"uli\">");
document.write("                            <li ><a href=\"shop.html\" class=\"aco\">Production<\/a><\/li>");
document.write("                            <li><a href=\"index.html#mission\" class=\"aco\">Mission<\/a><\/li>");
document.write("                            <li><a href=\"index.html#values\" class=\"aco\">Values<\/a><\/li>");
document.write("                            <li><a href=\"index.html#blog\" class=\"aco\">Blog<\/a><\/li>");
document.write("                            <a href=\"index.html\"><img src=\"images\/ru.png\" width=\"20%\"><\/a><br>");
document.write("                            <a href=\"index_en.html\"><img src=\"images\/eng.png\" width=\"20%\"><\/a>");
document.write("                        <\/ul>");
document.write("                    <\/nav>        ");
document.write("    <\/div>");
document.write("    <!-- Offcanvas Menu End -->");
document.write("      ");
document.write("    <!-- Header Section Begin -->");
document.write("    <header class=\"header\">");
document.write("        ");
document.write("        <div class=\"container\">");
document.write("            <div class=\"row\">");
document.write("                <div class=\"col-lg-3 col-md-3\">");
document.write("                    <div class=\"header__logo\" >");
document.write("                        <a href=\".\/index.html\"><img src=\"images\/logog\/logo_classic.png\" alt=\"\"><\/a>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <div class=\"col-lg-6 col-md-6\" style=\"padding-top: 30px;\">");
document.write("                    <nav class=\"header__menu mobile-menu\">");
document.write("                        <ul>");
document.write("                            <li><a href=\"shop.html\">Production<\/a><\/li>");
document.write("                            <li><a href=\"index.html#mission\">Mission<\/a>");
document.write("                            <\/li>");
document.write("                            <li><a href=\"index.html#values\">Values<\/a><\/li>");
document.write("                            <li><a href=\"index.html#blog\">Blog<\/a><\/li>");
document.write("                            <a href=\"index.html\"><img src=\"images\/ru.png\" width=\"10%\"><\/a>");
document.write("                            <a href=\"index_en.html\"><img src=\"images\/eng.png\" width=\"10%\"><\/a>");
document.write("                        <\/ul>");
document.write("                    <\/nav>");
document.write("                <\/div>");
document.write("                <div class=\"col-lg-3 col-md-3\" style=\"padding-top: 30px;\">");
document.write("                    <div class=\"header__nav__option\">");
document.write("                        <div class=\"\"><a href=\"rabota.new\/index.html\"><img src=\"images\/14(d)_en.png\" style=\"width: 80%; margin-top: -8px\"><\/a><\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"canvas__open\"><img src=\"images\/logog\/faf.png\"><\/div>");
document.write("        <\/div>");
document.write("    <\/header>");
document.write("    <!-- Header Section End -->");
document.write("<\/body>");
document.write("");
document.write("    <script src=\"js\/main.js\"><\/script>");
document.write("    <script src=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/jquery\/3.3.1\/jquery.min.js\"><\/script>");
document.write("<script src=\"https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/OwlCarousel2\/2.3.4\/owl.carousel.min.js\"><\/script>");
document.write("<\/html>");
